#pragma config(Sensor, in5,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_inch)
#pragma config(Motor,  port2,           Left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void off(){
	stopMotor(Left);
	stopMotor(Right);
	turnLEDOn(red);
	turnLEDOff(green);
}
void moveForward(){
	setMotor(Left, -127);
	setMotor(Right, -127);
	wait(.3);
}

void moveBackwards(){
	setMotor(Left, 127);
	setMotor(Right, 127);
	wait(.3);
}

void rotateCW(float time){
	setMotor(Left, -127);
	setMotor(Right, 127);
	wait(time);
}

void rotateCCW(float time){
	setMotor(Left, 127);
	setMotor(Right, -127);
	wait(time);
}

task main()
{

	while(1==1){
		while(SensorValue[potentiometer] < 3000){
			turnLEDOn(green);
			turnLEDOff(red);
			moveForward();
			moveBackwards();
			rotateCW(.3);
			moveForward();
			moveBackwards();
			rotateCCW(.6);
			moveForward();
			moveBackwards();
			rotateCW(.3);
		}
		while(SensorValue[potentiometer] > 3000){
			off();
		}
	}
}
