#pragma config(Sensor, in5,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  sonarLeft,      sensorSONAR_inch)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl10, sonarRight,     sensorSONAR_inch)
#pragma config(Motor,  port2,           Left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*DinkyBot 2.0 Will
1.Detect an object that is in front, left, or right of the RROBOTC
2.Make a decision based off where the object is to rotate away from it
3.repeat
*/

//core functionality of the robot here
/*void off(){
	stopMotor(Left);
	stopMotor(Right);
	turnLEDOn(red);
	turnLEDOff(green);
}*/
void remoteControl() {
	motor[Left]=-vexRT[Ch3];
	motor[Right]=-vexRT[Ch2];
}
void moveForward(){
	setMotor(Left, -127);
	setMotor(Right, -127);
}

void moveBackwards(){
	setMotor(Left, 127);
	setMotor(Right, 127);
	wait(.3);
}

void rotateCW(float time){
	setMotor(Left, -127);
	setMotor(Right, 127);
	wait(.3);
}

void rotateCCW(float time){
	setMotor(Left, 127);
	setMotor(Right, -127);
	wait(.3);

}



//when to do core functionality of the robot below
task main()
{
	while(1==1){
		while(SensorValue[potentiometer] < 3000){
			turnLEDOn(green);
			turnLEDOff(red);
			if(SensorValue[sonar] <= 10){
				//generate new random number
						int rNumber;
						float rTime;
						rTime = .6 + random(2.500);
						rNumber = random(500);
				//if > .5 ccw rotation
						if(rNumber > 250){
							moveBackwards();
							rotateCCW(rTime);
						}
				//else cw rotation
						else{
							moveBackwards();
							rotateCW(rTime);
						}
			}
			if(SensorValue[sonarLeft] < 5){
				//detects object then rotates away from object random cw rotation
					float rTime;
					rTime = .6 + random(2.500);
					moveBackwards();
					rotateCW(rTime);
			}
			if(SensorValue[sonarRight] < 5){
				//detects object then rotates away from object random ccw rotation
					float rTime;
					rTime = .6 + random(2.5);
					moveBackwards();
					rotateCCW(rTime);
			}
			else{
				//this code just makes the bot move forward if no object is detected
				moveForward();
				wait(.3);
			}
		}
		while(SensorValue[potentiometer] > 3000){
			remoteControl();
			turnLEDOn(red);
			turnLEDOff(green);
		}
	}
}
