#pragma config(Sensor, in5,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  sonar,          sensorSONAR_inch)
#pragma config(Motor,  port2,           Left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void off(){
	stopMotor(Left);
	stopMotor(Right);
	turnLEDOn(red);
	turnLEDOff(green);
}
void moveForward(){
	setMotor(Left, -127);
	setMotor(Right, -127);
}

void moveBackwards(){
	setMotor(Left, 127);
	setMotor(Right, 127);
	wait(.75);
}

void rotateCW(){
	setMotor(Left, -127);
	setMotor(Right, 127);
}

void rotateCCW(){
	setMotor(Left, 127);
	setMotor(Right, -127);
}


task main()
{
	while(1==1){
		while(SensorValue[potentiometer] < 3000){
			if(SensorValue[sonar] >= 10){
				turnLEDOn(green);
				turnLEDOff(red);
				moveForward();
				wait(.3);
			}
			else{
				moveBackwards();
				rotateCCW();
				wait(.5);
			}
		}
		while(SensorValue[potentiometer] > 3000){
			off();
		}
	}
}

/*Want to figure out how to incorporate alternation between cw and ccw.  might see how to incorporate other sensors to
try some different things with.  This version works!  V 1.1 a success!*/
